AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 10
CLASSES: 4
WEIGHTS: imagenet
LEARNING_RATE: 0.01

# Parameters for the callback
CALLBACKS:
  ReduceLROnPlateau:
    monitor: 'val_loss'
    factor: 0.1
    patience: 3
    min_lr: 1e-6